# Generated by Django 3.2.4 on 2023-05-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20230505_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AlterField(
            model_name='article',
            name='ids',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
