# Generated by Django 3.2.4 on 2023-05-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20230505_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='id',
            field=models.BigAutoField(
                auto_created=True, null=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='ids',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
